website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import *
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from .views import *
from faker import Faker
import random
from random import randrange

fake_data = Faker()

auth = Blueprint('auth', __name__)
global new_user


@auth.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.find_roomie'))
    else:
        if request.method == "POST":
            username = request.form.get('username')
            password = request.form.get('password')
            user = User.query.filter_by(username=username).first()
            if user:
                if check_password_hash(user.password, password):
                    login_user(user, remember=True)
                    return redirect(url_for('views.homepage'))
                else:
                    return render_template("login.html", comment="Username and/or incorrect!")
            else:
                return render_template("login.html", comment="Email does not exist")
    return render_template('login.html')


@auth.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.homepage'))


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.find_roomie'))
    else:
        if request.method == "POST":
            username = request.form.get("username")
            email = request.form.get("email")
            password = request.form.get("password")
            phone = request.form.get("phone")
            use_case_email = User.query.filter_by(email=email).first()
            use_case_phone = User.query.filter_by(phone_number=phone).first()
            use_case_username = User.query.filter_by(username=username).first()
            if use_case_email or use_case_phone or use_case_username:
                return render_template('register.html', confirmation="User already exists", user=current_user)
            new_user = User(email=email, password=generate_password_hash(password, method='sha256'), username=username,
                            phone_number=phone)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('views.additional_info'))
    return render_template("register.html", user=current_user)


@views.route("/find")
@login_required
def find_roomie():
    fake_name = []
    fake_text = []
    fake_hobbies = []
    fake_nums = []
    bios = [
        " I am currently a freshman student pursuing my Bachelor's degree in Law At VIPS, Delhi. I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At KIIT, Odisha. I love to do Community work and generally help people!",
        "I am currently a fresher at Chandigarh University pursuing my Bachelor's degree in Computer Applications . I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Fashion At Amity , Noida. I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At JIMS, Rohini. I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At VIPS, Rohini. I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Computer Applications from ASCM Panipath. I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At IMS Ghaziabad. I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At . I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Administration At IMS , Rohtak. I love to do Community work and generally help people!",
        ", I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At ABES Noida. I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Economics At JIMS, Rohini. I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At ABES Delhi. I love to play football and basketball and read comics in my free times",
        "I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At VIT Chennai.I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Medicine At BMSIT ,Bangalore I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At LPU . I love to do read books and to do coding in my free time",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At Benett University. I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Finance At Op Jindal, Sonipat.I love to do Community work and generally help people!",
        "I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At Vit Bhopal. I love to do Community work and generally help people!",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At IIT Bombay. I love to take part in Hackathons and to make projects!",
        " I am currently a freshman student pursuing my medical degree  at ASMC Pratapgarh . I love to do social help and to be a part of NGOs.",
        " I am currently a freshman student pursuing my Bachelor's degree in Computer Applications At IIT Madrass. I love to do Community work and generally help people!"]
    prifile_pic_list = []
    for i in range(5):
        fake_name.append(fake_data.name())
    for i in range(5):
        fake_text.append(random.choice(bios))
    my_skills = ["Reading", "Writing", "Movies", "Cooking", "Comedy", "Sports", "Marvel", "Anime", "Manga", "Cycling",
                 "Fitness", "Gymming", "Photography", "Coding", "Gaming", "Studying", "Travel", "Partying",
                 "Content Creation", "Languages", "Philosophy", "Binge watching", "Dancing", "Singing", "Song Writing",
                 "Beatboxing", "Martial arts", "Kdramas", "Public speaking", "Hollywood", "Painting"]
    for i in range(5):
        fake_nums.append(random.randint(0, 14))
    for i in range(5):
        fake_hobbies.append(random.sample(my_skills, 5))
    for i in range(5):
        num = random.randint(1,14)
        prifile_pic_list.append(num)

    fake_data_handler = zip(fake_name, fake_text, fake_hobbies, fake_nums,prifile_pic_list)
    # print(list(fake_data_handler))
    return render_template('find_roomie.html', user=current_user,
                           suggested_data=fake_data_handler)

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user, login_user
from .models import *
from faker import Faker

fake_data = Faker()

views = Blueprint('views', __name__)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
loginned = True


@views.route('/')
def homepage():
    return render_template("homepage.html", user=current_user)


@views.route('/about')
def about():
    return render_template("about.html", user=current_user)


@views.route("/info", methods=["POST", "GET"])
def additional_info():
    if current_user.is_authenticated:
        return redirect(url_for('views.find_roomie'))
    else:
        if request.method == "POST":
            f_name = request.form.get('f_name')
            l_name = request.form.get('l_name')
            addr = request.form.get('addr')
            city = request.form.get('city')
            state = request.form.get('state')
            zip = request.form.get('zip')
            country = request.form.get('country')
            college_name = request.form.get('college_name')
            course = request.form.get('course')
            branch = request.form.get('branch')
            year = request.form.get('year')
            h_1 = request.form.get('h1')
            h_2 = request.form.get('h2')
            h_3 = request.form.get('h3')
            h_4 = request.form.get('h4')
            h_5 = request.form.get('h5')
            bio = request.form.get('bio')
            new_user_info = GeneralInfo(f_name=f_name, l_name=l_name, address=addr, city=city, state=state, zip=zip,
                                        country=country, college=college_name, course=course, branch=branch, year=year,
                                        hobby_1=h_1, hobby_2=h_2, hobby_3=h_3, hobby_4=h_4, hobby_5=h_5)
            db.session.add(new_user_info)
            db.session.commit()
            login_user(new_user_info, remember=True)
            return redirect(url_for('auth.login'))
    return render_template('dashboard.html')

website/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{url_for('static',filename='style_about.css')}} />
<!--<link rel="stylesheet" href="style_homepage.css">-->
  <title>About Us</title>
</head>
<body>
  <div class="nav">
   <nav>
            <a href="{{url_for('views.homepage')}}" class="logo">ROOMIE</a>
          <a href="{{url_for('views.find_roomie')}}">Find a roomie</a>
          <a href={{url_for('views.about')}}>About</a>
          <a href={{url_for('auth.register')}}>Sign-up</a>
          <a href="{{url_for('auth.login')}}" >Sign-in</a>
           {% if user.is_authenticated %}
            <a href="{{url_for('auth.logout')}}" class="last">Logout</a>
           {% endif %}
      </nav>
      </div>
      <div class="container">
  <div class="card devrishi">
    <div class="imgBx">
      <img class="image" src={{url_for('static',filename='img/Devrishi_Sikka.png')}} />
    </div>
    <div class="contentBx">
      <h2>Devrishi Sikka</h2>
      <div class="size">
        <h3>Skills:</h3>
        <span>
          <img src="https://img.icons8.com/ios/30/ffffff/flask.png"/>
        </span>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/python.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/django.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/html.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/css.png"
        /></span>
        <span>
          <img src="https://img.icons8.com/metro/22/ffffff/mysql.png"
        /></span>
      </div>
      <div class="color">
        <h3>Contact :</h3>
        <span
          ><img src="https://img.icons8.com/ios-filled/22/ffffff/gmail-new.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/linkedin.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/ios-glyphs/22/ffffff/instagram-new.png"
          />
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/github.png"
        /></span>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="imgBx">
      <img class="image" src="{{url_for('static',filename='img/subham.png')}}" alt="Ojas" />
    </div>
    <div class="contentBx">
      <h2>Subham Ghosh</h2>
      <div class="size">
        <h3>Skills:</h3>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/java-coffee-cup-logo.png"/>
        </span>
        <span>
          <img src="https://img.icons8.com/ios-filled/22/ffffff/javascript-logo.png"/>
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/html.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/css.png"
        /></span>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/python.png"
        />
        </span>
        <span>
          <img src="https://img.icons8.com/ios-filled/22/ffffff/docker.png"/>
        </span>
        <span>
          <img src="https://img.icons8.com/windows/22/ffffff/kubernetes.png"/>
        </span>
      </div>
      <div class="color">
        <h3>Contact :</h3>
        <span
          ><img src="https://img.icons8.com/ios-filled/22/ffffff/gmail-new.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/linkedin.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/twitter--v1.png"/>
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/github.png"
        /></span>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="imgBx">
      <img class="image" src="{{url_for('static',filename='img/Arihant.png')}}"/>
    </div>
    <div class="contentBx">
      <h2>Arihant Bhardwaj</h2>
      <div class="size">
        <h3>Skills:</h3>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/python.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/django.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/html.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/css.png"
        /></span>
        <span>
          <img src="https://img.icons8.com/metro/22/ffffff/mysql.png"
        /></span>
      </div>
      <div class="color">
        <h3>Contact :</h3>
        <span
          ><img src="https://img.icons8.com/ios-filled/22/ffffff/gmail-new.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/linkedin.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/ios-glyphs/22/ffffff/instagram-new.png"
          />
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/github.png"
        /></span>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="imgBx">
      <img class="image ojas" src="{{url_for('static',filename='img/Aditya.png')}}"  />
    </div>
    <div class="contentBx">
      <h2>Aditya Chawla</h2>
      <div class="size">
        <h3>Skills:</h3>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/python.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/html.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/css.png"
        /></span>
        <span>
          <img src="https://img.icons8.com/metro/22/ffffff/mysql.png"
        /></span>
      </div>
      <div class="color">
        <h3>Contact :</h3>
        <span
          ><img src="https://img.icons8.com/ios-filled/22/ffffff/gmail-new.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/linkedin.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/ios-glyphs/22/ffffff/instagram-new.png"
          />
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/github.png"
        /></span>
      </div>
    </div>
  </div>
          <div class="card">
    <div class="imgBx">
      <img class="image" src="{{url_for('static',filename='img/ojas.png')}}"/>
    </div>
    <div class="contentBx">
      <h2>Ojas Aklecha</h2>
      <div class="size">
        <h3>Skills:</h3>
        <span>
          <img src="https://img.icons8.com/ios-glyphs/22/ffffff/python.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/django.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/html.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/material-outlined/22/ffffff/css.png"
        /></span>
        <span>
          <img src="https://img.icons8.com/metro/22/ffffff/mysql.png"
        /></span>
      </div>
      <div class="color">
        <h3>Contact :</h3>
        <span
          ><img src="https://img.icons8.com/ios-filled/22/ffffff/gmail-new.png"
        /></span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/linkedin.png"
        /></span>
        <span
          ><img
            src="https://img.icons8.com/ios-glyphs/22/ffffff/instagram-new.png"
          />
        </span>
        <span
          ><img src="https://img.icons8.com/ios-glyphs/22/ffffff/github.png"
        /></span>
      </div>
    </div>
  </div>
</div>
</body>
</html>















website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
       <link rel="stylesheet" href="{{url_for('static',filename='style_dashboard.css')}}">
<!--  <link rel="stylesheet" href="style_homepage.css">-->
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    <title>Roomie | Register</title>
  </head>
  <body>
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />

        <title>Roomie | Login</title>
      </head>
      <body>
<div class="nav">
                <nav>
               <a href="#" class="logo">ROOMIE</a>
               <a href={{url_for('views.about')}}>About</a>
               <a href={{url_for('auth.register')}}>Sign-up</a>
            </nav>
            </div>
          </a>
        </div>
       <div class="para">
        <h1>Additional Information</h1>

      </div>

      <div class="forms">
        <form method="post">
          <label for="fname">First name:</label><br>
          <input type="text" id="fname" class="fname" name="f_name" required><br>
          <label for="lname">Last name:</label><br>
          <input type="text" id="lname" class="lname" name="l_name" required>
          <label for="lname">Address:</label><br>
          <input type="text" id="lname" class="addr" name="addr" required>
          <label for="lname">City:</label><br>
          <input type="text" id="lname" class="city"  name="city" required>
          <label for="lname">State:</label><br>
          <input type="text" id="lname" class="state" name="state"required>
          <label for="lname">Zip Code:</label><br>
          <input type="text" id="lname" class="zip" name="zip" required>
          <label for="lname">Country:</label><br>
          <div class="country_drop">
          <input id="myInput" type="text" name="myCountry" autocomplete="off">
          </div>
          <label for="lname">College Name:</label><br>
          <div class="college_drop">
          <input id="college_name" type="text" name="myCountry" autocomplete="off">
          </div>
          <label for="lname">Course:</label><br>
         <div class="college_drop">
          <input id="course_name" type="text" name="myCountry" autocomplete="off">
          </div>
          <label for="lname">Year Of Admission:</label><br>
          <input type="text" id="lname" class="year" name="year" required>
            <h1 class="middle_title">About Yourself</h1>
            <p >( Please enter different hobbies so that we can serve you better! )</p>
            <div class="skill">
              <label for="lname">Hobbie 1:</label>
              <br>
              <input type="text" id="skills_one" name="h1" required autocomplete="off">
            </div>
            <div class="skill">
              <label for="lname">Hobbie 2:</label>
              <br>
              <input type="text" id="skills_two" name="h2" required autocomplete="off">
            </div>
            <div class="skill">
              <label for="lname">Hobbie 3:</label>
              <br>
              <input type="text" id="skills_three" name="h3" required autocomplete="off">
            </div>
            <div class="skill">
              <label for="lname">Hobbie 4:</label>
              <br>
              <input type="text" id="skills_four" name="h4" required autocomplete="off">
            </div>
            <div class="skill">
              <label for="lname">Hobbie 5:</label>
              <br>
              <input type="text" id="skills_five" name="h5" required autocomplete="off">
            </div>
            <label for="lname" class="bio_text">Add a cool bio so that people can know you better:</label><br>
         <textarea id="biography" name="bio" rows="4" cols="50">
        </textarea>

          <input type="submit" value="Sign up" class="sub">
        </form>
       </div>
       <script src="{{url_for('static',filename='country_auto.js')}}"></script>
       <script src="{{url_for('static',filename='college_auto.js')}}"></script>
       <script src="{{url_for('static',filename='course_auto.js')}}"></script>
       <script src="{{url_for('static',filename='skills_1.js')}}"></script>
       <script src="{{url_for('static',filename='skills_2.js')}}"></script>
       <script src="{{url_for('static',filename='skills_3.js')}}"></script>
       <script src="{{url_for('static',filename='skills_4.js')}}"></script>
       <script src="{{url_for('static',filename='skills_5.js')}}"></script>

      </body>
    </html>
  </body>
</html>

website/templates/find_roomie.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static',filename='find_roomie.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <title>Find A Roomie</title>
  </head>
  <body>
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Roomie-Finder</title>
      </head>
      <body>
        <div class="nav">
                <nav>
               <a href="{{url_for('views.homepage')}}" class="logo">ROOMIE</a>
               <a class="about" href={{url_for('views.about')}}>About</a>
                  {% if user.is_authenticated %}
            <a href="{{url_for('auth.logout')}}" class="last">Logout</a>
          {% endif %}
            </nav>

        </div>
        <div>

          {% for i in suggested_data %}
            <div class="cont">
              <h1 class="display">{{ i[0] }}</h1>
              <p class="para-2"> {{ i[1] }} </p>
              <p class="para-3">Hobbies: {{ i[2]|join(", ") }}</p>
              {% set num =   range(1, 13)|random %}
              {% if num == 1 %}
                <img  src={{url_for('static',filename='pfp/1.jpg')}}>
              {%elif num == 2%}
              <img  src={{url_for('static',filename='pfp/2.jpg')}}>
              {%elif num == 3%}
              <img  src={{url_for('static',filename='pfp/3.jpg')}}>
              {%elif num == 4%}
              <img  src={{url_for('static',filename='pfp/5.jpg')}}>
              {%elif num == 5%}
              <img  src={{url_for('static',filename='pfp/6.jpg')}}>
              {%elif num == 6%}
              <img  src={{url_for('static',filename='pfp/7.jpg')}}>
              {%elif num == 7%}
              <img  src={{url_for('static',filename='pfp/8.jpg')}}>
              {%elif num == 8%}
              <img  src={{url_for('static',filename='pfp/9.jpg')}}>
              {%elif num == 9%}
              <img  src={{url_for('static',filename='pfp/10.jpg')}}>
              {%elif num == 10%}
              <img  src={{url_for('static',filename='pfp/11.jpg')}}>
              {%elif num == 11%}
              <img  src={{url_for('static',filename='pfp/12.jpg')}}>
              {%elif num == 12%}
              <img  src={{url_for('static',filename='pfp/13.jpg')}}>
              {%elif num == 13%}
              <img  src={{url_for('static',filename='pfp/14.jpg')}}>
              {% endif %}
            </div>
        </div>
          {% endfor %}
      </body>
    </html>
  </body>
</html>

website/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{url_for('static',filename='style_homepage.css')}}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <title>Roomie</title>
</head>
<body>
  <div class="nav">
      <nav>
            <a href="{{url_for('views.homepage')}}" class="logo">ROOMIE</a>
          <a href="{{url_for('views.find_roomie')}}">Find a roomie</a>
          <a href={{url_for('views.about')}}>About</a>
          <a href={{url_for('auth.register')}}>Sign-up</a>
          <a href="{{url_for('auth.login')}}" >Sign-in</a>
          {% if user.is_authenticated %}
            <a href="{{url_for('auth.logout')}}" class="last">Logout</a>
          {% endif %}
      </nav>
  </div>
  <div class="container">
     <div class="tagline animate__animated animate__fadeInTopLeft   ">
      <h1>Choose your Roomie</h1>
      <h3>Live however you want</h3>
      <h3>Live with anyone you want</h3>
  </div>
  <div class="image animate__animated animate__fadeInBottomRight">
    <img src="{{ url_for('static',filename='img/homepage_group.png') }}" alt="group image" >
  </div>
  </div>

</body>
</html>

website/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static',filename='style_register.css') }}" />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    <title>Roomie | Register</title>
  </head>
  <body>
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Roomie | Registration</title>
      </head>
      <body>
          <div class="nav">
      <nav>
            <a href="{{url_for('views.homepage')}}" class="logo">ROOMIE</a>
          <a href="{{url_for('views.find_roomie')}}">Find a roomie</a>
          <a href={{url_for('views.about')}}>About</a>
          <a href={{url_for('auth.register')}}>Sign-up</a>
          <a href="{{url_for('auth.login')}}" >Sign-in</a>
          {% if user.is_authenticated %}
            <a href="{{url_for('auth.logout')}}" class="last">Logout</a>
          {% endif %}
      </nav>
  </div>
      <div class="image">
        <img src="{{ url_for('static',filename='img/registration_illustration.png') }}" alt="image" class="animate__animated animate__rotateIn">
        </div>
        <form method="post">
          <div class="container">
            <h1>Sign Up</h1>
            <p>Please fill in this form to create an account.</p>

            <label for="email"><b>Username</b></label>
            <input
              type="text"
              name="username"
              placeholder="Enter Username"
              required
            />
            <label for="email"><b>Email</b></label>
            <input
              type="text"
              placeholder="Enter Email"
              name="email"
              required
            />

            <label for="psw"><b>Password</b></label>
            <input
              type="password"
              placeholder="Enter Password"
              name="password"
              required
            />

            <label for="email"><b>Phone Number</b></label>
            <br />
            <input
              type="phone"
              name="phone"
              placeholder="Enter contact number"
              required />

            <p class="terms">
              By creating an account you agree to our
              <a href="#" class="terms"><b>Terms & Privacy</b></a>.
            </p>

            <div class="clearfix">
              <button type="submit" class="btn">Sign Up</button>
            </div>
                    <p class="error_message"> {{ confirmation }}</p>

          </div>
        </form>
          </a>
        </div>
      </body>
    </html>
  </body>
</html>